pulibrary/cicognara-rails

Gemfile, Gemfile.lock, app/models/book.rb, app/models/book_subject.rb, app/models/contributing_library.rb, app/models/creator.rb, app/models/creator_role.rb, app/models/role.rb, app/models/subject.rb, app/models/version.rb, db/migrate/20160502181000_create_creators.rb, db/migrate/20160502181007_create_roles.rb, db/migrate/20160502181014_create_subjects.rb, db/migrate/20160502181021_create_contributing_libraries.rb, db/migrate/20160502181041_create_books.rb, db/migrate/20160502181048_create_versions.rb, db/migrate/20160502182252_create_creator_roles.rb, db/migrate/20160502182306_create_book_subjects.rb, db/schema.rb, spec/models/book_spec.rb, spec/models/book_subject_spec.rb, spec/models/contributing_library_spec.rb, spec/models/creator_role_spec.rb, spec/models/creator_spec.rb, spec/models/role_spec.rb, spec/models/subject_spec.rb, spec/models/user_spec.rb, spec/models/version_spec.rb, spec/spec_helper.rb
=> Adding basic models

Gemfile, Gemfile.lock, app/models/marc_indexer.rb, spec/fixtures/cicognara.marc.xml, spec/models/marc_indexer_spec.rb
=> Adding unit test for MarcIndexer

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/books_controller.rb, app/controllers/contributing_libraries_controller.rb, app/controllers/users_controller.rb, app/controllers/versions_controller.rb, app/models/ability.rb, app/models/user.rb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20160505124159_add_role_to_user.rb, db/schema.rb, spec/controllers/books_controller_spec.rb, spec/controllers/contributing_libraries_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/controllers/versions_controller_spec.rb, spec/features/contributing_libraries_spec.rb, spec/features/versions_spec.rb, spec/models/ability_spec.rb, spec/models/user_spec.rb, spec/rails_helper.rb, spec/requests/contributing_library_spec.rb, spec/requests/versions_spec.rb, spec/support/login_helper.rb
* Users can't interact with AR models at all
* Curators can view Books, CRUD Versions
* Admins can CRUD Books, Versions and other Users
Closes #17
=> Adding roles and Ability

README.md, lib/tasks/set_admin_role.rake
=> Addig rake task to make users admins

app/controllers/catalog_controller.rb, app/controllers/versions_controller.rb, app/models/marc_indexer.rb, app/views/catalog/_show_default.html.erb, app/views/catalog/_show_default_inner.html.erb, app/views/catalog/_show_linked_books.html.erb, spec/controllers/catalog_controller_spec.rb, spec/controllers/versions_controller_spec.rb
=> Showing books related to a Catalog entry

README.md, app/controllers/catalog_controller.rb, app/models/marc_indexer.rb, app/models/search_builder.rb, lib/cicognara/catalogo_item.rb, lib/cicognara/tei_indexer.rb, lib/tasks/tei.rake, solr/config/solrconfig.xml, spec/cicognara/tei_indexer_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/fixtures/cicognara.marc.xml, spec/models/marc_indexer_spec.rb, spec/requests/catalog_spec.rb
Closes #58, advances #56, advances #11
=> indexes marc fields on catalogo entry, hides marc from search results

lib/cicognara/catalogo_item.rb, spec/cicognara/tei_indexer_spec.rb
=> Using MARC title for display title

.gitignore, Gemfile, Gemfile.lock, app/views/layouts/catalogo_section.html.erb, config/initializers/high_voltage.rb, lib/xsl/partials.xsl
- Adds section partials. Closes #75.
- Path for partials set to app/views/pages/catalogo. Closes #87.
- Updated XSL write-to path. Closes #86.
=> High voltage

README.md, lib/cicognara/catalogo_item.rb, lib/tasks/tei.rake, lib/xsl/partials.xsl, spec/cicognara/tei_indexer_spec.rb, spec/fixtures/cicognara.tei.xml, spec/rails_helper.rb, spec/requests/partials_spec.rb
=> adds rake task to generate section partials, update catalogo.tei fixture

app/assets/stylesheets/catalogo.scss, app/assets/stylesheets/scaffolds.scss, lib/tasks/tei.rake, lib/xsl/partials.xsl, spec/requests/partials_spec.rb
Advances #78. Still need link back to partial from catalog.
=> Catalogo styling

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/models/marc_indexer.rb, app/views/catalog/_show_header_default.html.erb, lib/cicognara/catalogo_item.rb, lib/cicognara/tei_indexer.rb, lib/xsl/partials.xsl, spec/cicognara/tei_indexer_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/requests/catalog_spec.rb, spec/requests/partials_spec.rb
Adds section number to solr document to enable link from catalog to catalogo. Closes #78.
=> creates link from catalog to and from catalogo on item number

app/helpers/application_helper.rb, lib/cicognara/catalogo_item.rb, lib/cicognara/tei_indexer.rb, spec/cicognara/tei_indexer_spec.rb, spec/fixtures/cicognara.tei.xml, spec/requests/catalog_spec.rb
Closes #101. Updates tei fixture.
=> changes tei_indexer to use just the main seg of a section head.

app/controllers/catalog_controller.rb, spec/requests/catalog_spec.rb
=> allow tei item catalog view to render when marc record is missing

lib/xsl/partials-section.xsl, spec/requests/partials_spec.rb
=> Navigate catalogo

lib/xsl/partials-item.xsl
The xslt wasn't descending into embedded divs.
=> fixes xpath to catalogo items; closes #124

app/assets/stylesheets/components/_record.scss, app/controllers/catalog_controller.rb, app/views/catalog/_show_header_default.html.erb
@jpstroop is this what you had in mind?
=> Remove Catalogo Item heading on show page

Gemfile.lock, config/solr_wrapper_test.yml
I was having problems running Solr locally, and updating the solr_wrapper config fixed this for me.
=> Updating Solr config

app/models/marc_indexer.rb, lib/tasks/tei.rake, spec/controllers/books_controller_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/contributing_libraries_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/controllers/versions_controller_spec.rb
* Fix controller test deprecations
* Don't dump XSL output to console
* Make Traject's log level configurable (WARN by default)
=> Deprecations and logging

app/controllers/catalog_controller.rb, app/models/marc_indexer.rb, lib/cicognara/catalogo_item.rb, spec/features/search_spec.rb
=> Adding Genre, Name, and Section facets

Rakefile, app/controllers/catalog_controller.rb, spec/features/view_spec.rb
=> Making name and subject field values links to searches.

app/controllers/catalog_controller.rb, spec/features/view_spec.rb
=> Search by id field.

solr/config/schema.xml, spec/features/search_spec.rb, spec/features/view_spec.rb
=> Trimming list of fields for populating auto-suggest

app/assets/stylesheets/components/_forms.scss, spec/views/versions/new.html.erb_spec.rb
=> CSS fix for hidden checkbox

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_menu.scss, app/views/shared/_admin_menu.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_front_header.html.erb, app/views/shared/_header_navbar.html.erb, app/views/shared/_user_util_links.html.erb, spec/features/view_spec.rb, spec/support/login_helper.rb
Adds admin menu in header and discrete login link in footer.
Fixes #150, Fixes #151
=> Adding admin menu

app/controllers/catalog_controller.rb, app/models/book.rb, app/models/entry.rb, app/models/version.rb, lib/cicognara/book_indexer.rb, lib/cicognara/bulk_entry_indexer.rb, lib/cicognara/catalogo_item.rb, lib/cicognara/tei_indexer.rb, lib/cicognara/with_book_cache.rb, spec/controllers/books_controller_spec.rb, spec/controllers/contributing_libraries_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/controllers/versions_controller_spec.rb, spec/features/search_spec.rb, spec/features/versions_spec.rb, spec/models/book_spec.rb
=> Index and auto-update contributing institution.

app/controllers/catalog_controller.rb, app/models/book.rb, spec/features/search_spec.rb, spec/models/book_spec.rb
=> Index if digitized version exists.

app/controllers/catalog_controller.rb, lib/cicognara/catalogo_item.rb, spec/models/entry_spec.rb
=> Sort by catalogo nr.

lib/cicognara/section.rb, lib/cicognara/tei_indexer.rb, lib/cicognara/with_book_cache.rb
This gets a full index on staging from 20m to 7. Locally it went from
10m to 1m.
I can't get it any quicker without upsert support, which Postgres has, but SQLite doesn't.
=> Speed up ingest

app/controllers/catalog_controller.rb, app/models/marc_indexer.rb, lib/cicognara/catalogo_item.rb, spec/features/view_spec.rb
=> update subject and name search links

.rubocop.yml, app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/features/search_spec.rb, spec/support/devise.rb
=> Stops welcome text from ever rendering.

.gitignore, config/deploy.rb
=> Save downloaded MARC and TEI files to /public so they can be served

app/assets/stylesheets/components/_forms.scss, app/views/pages/about.html.erb
closes #197 
Also pads the search field dropdown. I thought @axamei had made an issue, but I can't find it now.
=> Swap images around per Sandy. Pad dropdown.

app/models/marc_indexer.rb, spec/models/marc_indexer_spec.rb
=> removes fondo cigonara from name facet and excludes uris from display

app/models/book.rb, app/models/solr_document.rb, app/views/catalog/_universal_viewer_default.html.erb, spec/models/book_spec.rb, spec/views/catalog/_universal_viewer_default.html.erb_spec.rb
=> Index manifests and hide viewer when empty.

app/helpers/application_helper.rb, config/routes.rb, lib/xsl/partials-section.xsl, spec/requests/catalog_spec.rb, spec/requests/partials_spec.rb, spec/routing/high_voltage_routing_spec.rb
=> Remove index.html from static pages

app/models/user.rb, config/initializers/devise.rb
* Increasing time sync leeway
* Removing reference to missing 'name' attribute
=> Fix Google OAuth2 login

app/views/pages/news.html.erb
Could I get a merge and deploy please?
=> New news item

config/deploy.rb
=> update marc and tei to catalog v2.0

app/models/book.rb, lib/cicognara/catalogo_item.rb, spec/models/book_spec.rb, spec/models/entry_spec.rb
=> Indexing a single value for the digital content availability

app/views/pages/microfiche_copyright.html.erb
=> Adding microfiche_copyright static page

app/models/marc_indexer.rb
Fixes indexing issue with multiple author_display values
=> Making sure author_display isn't multi-valued

app/views/catalog/_linked_books_default.html.erb
This avoids the immediate problem, but I've created https://github.com/pulibrary/cicognara-rails/issues/229 to figure out what the underlying logic or data problem is.
=> Workaround error with linked books

app/controllers/catalog_controller.rb
=> Allow ascending and descending date sort

app/models/book.rb, lib/cicognara/catalogo_item.rb, spec/features/search_spec.rb, spec/models/book_spec.rb, spec/models/entry_spec.rb
=> Change boolean labels to Yes/No

app/views/catalog/_linked_books_default.html.erb
=> Only show MARC records on item show page (Catalogo entry is already at the top of the page)

app/controllers/catalog_controller.rb, app/models/marc_indexer.rb, spec/features/view_spec.rb
=> Disply more MARC metadata

config/environments/development.rb
I didn't catch this change in https://github.com/pulibrary/cicognara-rails/pull/252/files#diff-a2f09e1db7a47eb67c5849478a97f3d7R13
=> consider all requests local in dev for debug

.rubocop.yml, app/controllers/catalog_controller.rb, app/models/marc_indexer.rb, lib/tasks/csv.rake, spec/features/view_spec.rb, spec/models/marc_indexer_spec.rb
=> New marc display fixes

config/locales/blacklight.en.yml
=> update contact email

app/models/iiif/book_collection.rb, spec/models/iiif/entry_collection_spec.rb
=> Using version labels, and sorting microfiche last

app/controllers/catalog_controller.rb, spec/features/view_spec.rb
=> update the ordering and metadata display

app/assets/stylesheets/components/_viewer.scss, app/views/catalog/_universal_viewer_default.html.erb, spec/views/catalog/_universal_viewer_default.html.erb_spec.rb
=> Updating label to show DCL#, put contributor on separate line

.rubocop.yml, Gemfile, Gemfile.lock, app/models/book.rb, spec/cicognara/tei_indexer_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/versions_controller_spec.rb, spec/features/search_spec.rb, spec/features/versions_spec.rb, spec/features/view_spec.rb, spec/fixtures/files/manifests/1.json, spec/fixtures/files/manifests/2.json, spec/fixtures/files/manifests/3.json, spec/models/book_spec.rb, spec/models/entry_spec.rb, spec/requests/catalog_spec.rb, spec/requests/search_field_spec.rb, spec/requests/versions_spec.rb, spec/spec_helper.rb, spec/support/stub_manifest.rb
=> Index range labels

config/database.yml, db/schema.rb
=> Use postgres in development

config/deploy.rb
Update app to use current version of data from https://github.com/pulibrary/cicognara-catalogo/
=> Use current master version of catalogo

.circleci/config.yml
Copied from https://github.com/pulibrary/pulmap/pull/622/commits/faa16d56305e45c0487f6e9962f54a5a654c7d19
=> Modify the way solr is loaded in circle

app/controllers/catalog_controller.rb
Making sure these changes for Solr 7.7 also work on Solr 7.1
=> modify catalog controler solr params to be compatible with 7.7

app/controllers/catalog_controller.rb
Oops. Not that anyone uses the spelling suggestions, but I think I accidentally broke them.
=> set catalog controller solr_parameters once per field

README.md
=> Update README to make dev setup easier.

.circleci/config.yml, Gemfile.lock, db/schema.rb
Maybe someone could try this branch and see if it's universal?
=> Updates that came with my dev setup

lib/tasks/getty.rake
=> Use default Rails logger for getty import task

app/services/getty_parser/importer.rb
=> Use a transaction per-record instead of for entire getty import

README.md, Rakefile, lib/tasks/dev.rake
Now there's:
cico:development # runs dev solr
cico:test # runs test solr
cico:development:server # runs dev solr, rails server, and seeds tei
fixes #414
=> Update development rake task names

README.md
=> Update user creation documentation in README

app/assets/javascripts/application.js
=> Load the right viewer in Javascript

.rubocop.yml, app/models/solr_document.rb, app/models/version.rb, app/services/getty_parser/getty_record.rb, app/services/getty_parser/importer.rb, app/views/catalog/_universal_viewer_default.html.erb, db/migrate/20191115173414_add_imported_metadata_to_versions.rb, db/schema.rb, scripts/context_combiner.rb, spec/fixtures/resources/gri_9923593930001551.json, spec/fixtures/resources/gugg_1710929.json, spec/fixtures/resources/met_00573979.json, spec/fixtures/resources/uh_urnnbndebsz16-diglit-32330.json, spec/models/version_spec.rb, spec/services/getty_parser/getty_record_spec.rb, spec/services/getty_parser_spec.rb, spec/views/catalog/_universal_viewer_default.html.erb_spec.rb
And index to it during getty import
advances #334
=> Add imported_metadata field to Version

app/assets/javascripts/application.js, app/assets/stylesheets/components/_record.scss, app/controllers/catalog_controller.rb, app/helpers/show_helper.rb, app/views/catalog/_linked_books_default.html.erb, app/views/catalog/_version_tabs_default.html.erb, spec/views/catalog/_version_tabs_default.html.erb_spec.rb
=> 334 metadata swapping

LICENSE
=> Adding License (Apache 2)

app/services/getty_parser/importer.rb
Fixes an issue where all versions got deleted every loop.
=> Moves version delete out of import loop.

config/partners.yml
Closes https://github.com/pulibrary/cicognara-catalogo/issues/147
=> Fix link to MET.

config/partners.yml
=> Fixing wording of National Gallery, London

Gemfile, Gemfile.lock
This is necessary in order to advance #473
=> Updating the mimemagic Gem dependency (along with the related `puma` and `pg` dependencies)

app/assets/stylesheets/components/_facets.scss
Closes #451 
---
https://user-images.githubusercontent.com/7795797/148268711-ea1c6f93-1375-4ef1-8a2a-30499e04a2d0.mov
=> Changed position to keep facets from spilling over into footer

app/views/pages/catalogo/_item_3031.html, app/views/pages/catalogo/_item_733.html, app/views/pages/catalogo/section_1.6.html, app/views/pages/catalogo/section_2.5.html
Views updated in my local environment, probably as a result of running one the rake tasks indicated in the README to get started, but not really sure.
=> Views updated in my local environment

app/views/shared/_front_header.html.erb, app/views/shared/_user_util_links.html.erb
=> Added Partners link to correct area of site menu outside of homepage

app/assets/stylesheets/components/_results.scss, app/assets/stylesheets/components/_section.scss
=> Updated CSS

app/controllers/catalog_controller.rb, spec/features/advanced_search_spec.rb
=> Switched default sort

.circleci/config.yml
=> Updating the CircleCI configuration to support Node.js 12.x releases

app/controllers/catalog_controller.rb
=> Remove relevance from search sort

app/views/shared/_header_navbar.html.erb, app/views/shared/_this_is_beta.html.erb
=> Remove beta banner

README.md
Updated deployment notes after last release.
=> Deployment notes

.gitignore, app/assets/stylesheets/components/_community.scss, app/views/pages/research.html.erb, app/views/shared/_front_header.html.erb, app/views/shared/_user_util_links.html.erb
Draft of research page for review in staging
=> Adding Research page to Community menu
