- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- config/initializers/0_coverage.rb
- spec/cicognara/tei_indexer_spec.rb
- spec/spec_helper.rb
* Initializer runs before User model is used in other initializers
* Removing Coveralls integration because it isn't working
* Coverage is reported in CircleCI build and report is available in the Circle Artifiacts, e.g.: https://circle-artifacts.com/gh/pulibrary/cicognara-rails/68/artifacts/0/tmp/circle-artifacts.Zi5ovJ8/coverage/index.html
> Move coverage setup to initializer

- app/controllers/catalog_controller.rb
- app/models/marc_indexer.rb
- spec/fixtures/cicognara.marc.xml
- spec/models/marc_indexer_spec.rb
- spec/requests/catalog_spec.rb
Updates marc indexer configuration and creates a Book object with the cico number for each MARC record. Uses existing rake task: `MARC_FILE='PATH TO FILE' rake solr:marc:index`
Warning - sqlite can't handle so many writes at once but postgres should be able.
> Index marc

- app/helpers/application_helper.rb
- config/deploy.rb
- config/deploy/staging.rb
- lib/tasks/tei.rake
- lib/xsl/partials-item.xsl
- lib/xsl/partials-section.xsl
Capistrano deploy config can now reference a specific tag or branch. Closes #90.
Index solr and regenerate partials on deploy.
> pull specific catalogo version on deploy

- app/assets/stylesheets/components/_variables.scss
- app/views/_user_util_links.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_front_header.html.erb
- app/views/shared/_header_navbar.html.erb
- config/deploy.rb
- config/environments/staging.rb
- config/routes.rb
- spec/routing/high_voltage_routing_spec.rb
Currently deployed. Updated cicognara-catalog version. Change routes to allow links/assets to work with relative root url in staging environment.
http://libruby-dev.princeton.edu/cicognara/catalog/1978
> update static page routes

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_alerts.scss
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_this_is_beta.html.erb
Beta banner from pulmap app is fixed so doesn't scroll off top. Behavior copied here. Is this desirable?
> Adds beta banner. Closes #176

- README.md
- config/deploy.rb
- lib/tasks/tei.rake
Clearing out the old Solr index shouldn't have any dire consequences if it is triggered on each deploy right?
> delete old solr index before adding new docs

- app/assets/stylesheets/components/_variables.scss
In Firefox, Source Sans Pro has extra spacing after characters with diacritics, but Helvetica displays them correctly.
Fixes #278
> Removing Google font with diacritic spacing problems in favor of Helvetica

- .rubocop.yml
- app/controllers/catalog_controller.rb
- app/models/book.rb
- app/views/catalog/_index_links_default.html.erb
- app/views/shared/_front_header.html.erb
- app/views/shared/_header_navbar.html.erb
- lib/cicognara/catalogo_item.rb
- spec/features/search_spec.rb
- spec/models/book_spec.rb
- spec/models/entry_spec.rb
- spec/views/catalog/_index_links_default.html.erb_spec.rb
* Facets ordered in desired order of metadata display
* Digital Content facet now has Microfiche/Matching/None options
Fixes #300, Fixes #301, Fixes #302, Fixes #303
> Reordering facets, reworking digital content facet

- Gemfile
- Gemfile.lock
Addresses [CVE-2018-16470](https://nvd.nist.gov/vuln/detail/CVE-2018-16470), [CVE-2018-16471](https://nvd.nist.gov/vuln/detail/CVE-2018-16471), and [CVE-2018-16468](https://nvd.nist.gov/vuln/detail/CVE-2018-16468)
> Updates rack to 2.0.6 and loofah to 2.2.3

- Gemfile.lock
- config/deploy.rb
Creates new Capistrano task to separate reindexing from the deployment.
Invoked with `cap production deploy:reindex`.
Closes #235
> Separate deploy from reindexing

- config/deploy.rb
- spec/models/marc_indexer_spec.rb
* Use updated MARC/TEI from https://github.com/pulibrary/cicognara-catalogo
* Link `app/views/pages/catalogo` directory to preserve generated pages across deploys
Fixes #317
> Use updated MARC/TEI data, preserve static pages across deployments

- .rubocop.yml
- app/models/book.rb
Production is running 2.3 and does not have the `&.` operator.
> Don't use &. operator

- app/assets/stylesheets/components/_facets.scss
This proposes to resolve a bug found when users expand facet panels: https://cicognara.org/catalog?q=&search_field=all_fields
> Resolves a styling bug rendering the facet panel under the footer

- config/deploy.rb
- config/deploy/production.rb
- lib/tasks/tei.rake
Relates to #338 and addresses the following:
- Separates the Rake task for downloading catalogo TEI and MARC into the `tei:catalogo:update` task
- Ensures that the Capistrano task `deploy:reindex` downloads the catalogo first before indexing
- Updates the production server and deployment directory
> Updates the Capistrano deployment configuration and tasks for the production environment

- app/views/pages/checklist.html.erb
- app/views/pages/faq.html.erb
* Using "Manifest URI" instead of "URI"
* Linking to IIIF manifest validator
* Removing FTP as option for sending data to Getty
Fixes #351
> Updating FAQ and metadata checklist

- spec/spec_helper.rb
> Ensures that the TEI partials are not generated before test suites are run

- config/deploy.rb
- lib/xsl/partials-section.xsl
I added type attributes to the preface divs in `cicognara-catalogo/catalogo.tei.xml` (type="preface") and then modified two templates to process preface divs as well as section divs.
> Extends two templates to process prefaces as well as sections.

- Rakefile
- lib/tasks/tei.rake
Add it back separately in deploy task.
Also set server task to run solr_wrapper with persist: true
Now our dev indexes should persist between runs of the server task
fixes #402
> Move solr deletion out of tei:index

- config/schedule.rb
Mondays was a fine time, but we forgot to deploy; just changing it so we
can ensure it works while we're on this sprint
> Load getty import on Tuesdays

- app/assets/javascripts/application.js
- app/views/catalog/_universal_viewer_default.html.erb
- spec/views/catalog/_universal_viewer_default.html.erb_spec.rb
Adds a data-version-id attribute on the manifest tabs and properly retrieves it in the toggle code.
> Fixes #436

- config/database.yml
Fixes database being wiped between deploys because of an unshared sqlite
db file.
> Use Postgres in staging.

- app/services/getty_parser/importer.rb
- spec/services/getty_parser_spec.rb
The previous method didn't run traject over all books at once.
> Speed up Getty reindexing.

- lib/cicognara/catalogo_item.rb
- spec/cicognara/tei_indexer_spec.rb
- spec/fixtures/cicognara.marc.xml
- spec/models/marc_indexer_spec.rb
Stores in Solr the publication year from the TEI data (when available) to make sure the order makes sense to the user. This is important because we display the year in the TEI data to the user and this make sure the order is evident to them.
Fixes #439 
We still have the issue that a record might not show a date (because there is none in TEI) but the record will display between records with dates (see record 3455 in the screenshot below). This is happening because we are preserving the publication date in MARC (in this case is 1834). We could always overwrite the publication year with the TEI  data even if that means losing the value that we picked from MARC, I not sure we want to do that but it is an option that will prevent users from getting confused.
> Fixes sort by year bug

- app/controllers/catalog_controller.rb
- app/helpers/show_helper.rb
- app/views/catalog/_version_tabs_default.html.erb
- spec/features/view_spec.rb
Switches the subject field used for searching when clicking on a Show page subject. We were using a text tokenized field (`subject_t`) in the Show page and but we use a string field (`subject_topic_facet`) in the Search page. 
Field `subject_topic_facet` field is a String field and that's the correct field to use for faceting. Faceting on tokenized fields like `subject_t` is a no-no.
We also store slightly different values in `subject_t` vs `subject_topic_facet`, it looks like we consolidate term variations into a single root subject. For example we store "Medicine—Early works to 1800" in the `subject_t` field vs faceted as just "Medicine" in the `subject_topic_facet`. The code accounts for this.
This addresses the failed subject searches in #443, but there are other fields to fix so it …
> Issue 443 subject search

- config/schedule.rb
- lib/tasks/getty.rake
- lib/tasks/tei.rake
Force rake tasks to run sequentially when scheduled and added some logging.
Fixes #539 for real
I had to create a new rake task to execute the steps sequentially since `whenever` didn't allowed me to call more than one rake task on the definition.
> Force rake tasks to run sequentially
